config/routes.rb
RReader::Application.routes.draw do
  get "settings/import_export"

  post "settings/do_import"

  get "settings/do_export"

  devise_for :users

  get "home/index"

  get "home/starred"

  get "home/trash"

  get "home/trends"

  get "home/settings"

  put "feed_entries_actions/star_items"

  put "feed_entries_actions/unstar_items"

  put "feed_entries_actions/mark_as_read"

  put "feed_entries_actions/mark_as_unread"

  delete "feed_entries_actions/remove_items"

  put "feed_entries_actions/restore_items"

  resources :rss_streams

  resources :feed_entries do
    member do
      get 'show'
      delete 'destroy'
    end
  end

  root :to => 'home#index'

end

app/controllers/settings_controller.rb
include OpmlParser

class SettingsController < ApplicationController
	def import_export
		respond_to do |format|
			format.html
			format.json
			format.js
		end
	end

	def do_import
		opml_file = params[:file]
		outlines = OpmlParser::import(opml_file.read)
		@stream_with_error = nil

		outlines.each do |outline|
			stream = RssStream.new
			stream.title = outline.attributes[:title]
			stream.url = outline.attributes[:xmlUrl]
			stream.user_id = current_user.id
			if !stream.save
				@stream_with_error = stream
				break
			end
		end

		@streams = RssStream.all_by_title(current_user.id)

		respond_to do |format|
			format.json
			format.js
		end
	end

	def do_export
	end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_import_export.html.haml
%h4 Import OPML file
= form_tag(settings_do_import_path + ".js", :method => "post", :remote => true, :multipart => true) do
  %p
    .fileupload.fileupload-new{:data => {:provides => "fileupload"}}
      %span.btn.btn-file
        %span.fileupload-new
          %i.icon-file-alt
          Select file
        %span.fileupload-exists Change
        %input{:type => "file", :name => "file"}
      %span.fileupload-preview
        %a.close.fileupload-exists{:href => "#", |
                                   :data => {:dismiss => "fileupload"}, |
                                   :style => "float: none"} x
      &nbsp;
      = submit_tag("Import", :class => "btn btn-info")
  %br

%h4 Export as OPML
%p Not implemented yet

app/views/settings/do_import.js.erb
<% if @stream_with_error.present? %>
	$.notify('error occured while importing OPML', 'error')
<% else %>
	var html = "<%= escape_javascript(
		render('home/streams', :collection => @streams)) %>"
	$("#streams_list").html(html)
	$.notify('OPML successfully imported!', 'success')
<% end %>

app/views/settings/import_export.js.erb
var html = "<%= escape_javascript(
  render(:partial => 'settings/import_export')) %>"

$("#settings-container").html(html);