config/routes.rb
RReader::Application.routes.draw do
  get "settings/import_export"

  post "settings/do_import"

  get "settings/do_export"

  devise_for :users

  get "home/index"

  get "home/starred"

  get "home/trash"

  get "home/trends"

  get "home/settings"

  put "feed_entries_actions/star_items"

  put "feed_entries_actions/unstar_items"

  put "feed_entries_actions/mark_as_read"

  put "feed_entries_actions/mark_as_unread"

  delete "feed_entries_actions/remove_items"

  put "feed_entries_actions/restore_items"

  resources :rss_streams

  resources :feed_entries do
    member do
      get 'show'
      delete 'destroy'
    end
  end

  root :to => 'home#index'

end

app/models/rss_stream.rb
class RssStream < ActiveRecord::Base
  attr_accessible :title, :url, :user_id

  before_save :handle_empty_title

  has_many :feed_entries, :dependent => :destroy
  belongs_to :user

  validates :title, :presence => true, :on => :update
  validates :url, :format => {
    :with	 => /^https?:\/\/.+\.[a-z]{2,4}\//i,
    :message => 'must be a valid'
  }

  scope :all_by_title, lambda { |id| where(:user_id => id).order("UPPER(title) ASC") }

  # loads all entrie
  def load_feed_entries
    last_entry = self.feed_entries.last
    if last_entry.nil?
      feed = Feedzirra::Feed.fetch_and_parse(self.url)
    else
      feed = Feedzirra::Feed.fetch_and_parse(self.url,
        :if_modified_since => last_entry.published_at.to_time)
    end

    # update the feed title if required and possible
    if !feed.nil? && !feed.title.nil? && self.title != feed.title
      self.update_attributes({:title => feed.title})
    end

    RssStream.add_entries(feed.entries, self.id, self.user_id)
  end

  # updates the entries of the given URLs
  def self.update_all_feeds(urls, current_id)
    Feedzirra::Feed.fetch_and_parse(urls,
      :on_success => lambda { |url, feed|
        rss = RssStream.select("rss_streams.id").where(:url => url).first
        RssStream.add_entries(feed.entries, rss.id, current_id)
      }
    )
  end

  private
    def self.add_entries(entries, stream_id, current_id)
      entries.each do |entry|
          unless FeedEntry.joins(:rss_stream).where("rss_streams.user_id = ?", current_id).exists?(:guid => entry.id)
            FeedEntry.create!(
              :name          => entry.title,
              :summary       => entry.summary,
              :url           => entry.url,
              :content       => entry.content,
              :published_at  => entry.published,
              :guid          => entry.id,
              :rss_stream_id => stream_id,
              :read          => false
            )
          end
      end
    end

    def handle_empty_title
      self.title = "unknown" if title.nil? || title.empty?
    end
end

app/controllers/rss_streams_controller.rb
class RssStreamsController < ApplicationController
  # GET /rss_streams
  # GET /rss_streams.json
  def index
    @rss_streams = RssStream.where(:user_id => current_user.id)

    respond_to do |format|
      format.html
      format.json { render json: @rss_streams }
      format.js
    end
  end

  # GET /rss_streams/1
  # GET /rss_streams/1.json
  def show
    @rss_stream = RssStream.where(:id => params[:id]).first
    @rss_stream.load_feed_entries
    @entries = FeedEntry.all_by_stream(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @rss_stream }
      format.js
    end
  end

  # GET /rss_streams/new
  # GET /rss_streams/new.json
  def new
    @rss_stream = RssStream.new

    respond_to do |format|
      format.html
      format.json { render json: @rss_stream }
      format.js
    end
  end

  # GET /rss_streams/1/edit
  def edit
    @rss_stream = RssStream.find(params[:id])
  end

  # POST /rss_streams
  # POST /rss_streams.json
  def create
    new_feed = params[:rss_stream]
    @rss_stream = RssStream.new
    @rss_stream.title = new_feed[:title]
    @rss_stream.user_id = current_user.id

    # Find RSS or Atom feed at the given URL and update the RssStream
    @rss_stream.url = Feedbag.find(new_feed[:url]).first

    respond_to do |format|
      if @rss_stream.save
        @rss_stream.load_feed_entries
        @streams = RssStream.all_by_title(current_user.id)
        format.html
        format.json { render json: @rss_stream }
        format.js
      else
        format.html
        format.json { render json: @rss_stream.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PUT /rss_streams/1
  # PUT /rss_streams/1.json
  def update
    @rss_stream = RssStream.find(params[:id])

    respond_to do |format|
      if @rss_stream.update_attributes(params[:rss_stream])
        @streams = RssStream.all_by_title(current_user.id)
        @stream_title = @rss_stream.title
        format.html
        format.json { head :no_content }
        format.js
      else
        format.html
        format.json { render json: @rss_stream.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /rss_streams/1
  # DELETE /rss_streams/1.json
  def destroy
    @rss_stream = RssStream.find(params[:id])
    @rss_stream.destroy

    @streams = RssStream.all_by_title(current_user.id)
    @entries = FeedEntry.order("id DESC").limit(5)

    respond_to do |format|
      format.html
      format.json { head :no_content }
      format.js
    end
  end
end

app/helpers/rss_streams_helper.rb
module RssStreamsHelper
end

app/views/rss_streams/_edit.html.haml
= render 'form'

app/views/rss_streams/_entries.html.haml
%form#entries-form{"data-remote" => "true"}
  %table#entries
    - if @entries.present?
      - @entries.each do |entry|
        %tr
          %td.chckbx
            = check_box_tag 'items[]', entry.id
          %td.title
            = star_icon(entry).html_safe
            \&nbsp;
            \#{link_to(entry.name, entry, { :remote => true, :class => read_or_not(entry), :title => entry.name })}
          %td.date
            %em{:style => "color: gray;"}= pretty_date(entry.published_at)
    - else
      %p There are no items here yet
:javascript
  $('form#entries-form input[type="checkbox"]').click(function() {
      var num_selected = $('form#entries-form input:checked').length;
      if (num_selected == 1 && !entries_selected) {
        $('#entries-selector').attr('checked', 'checked');
        $.toggle_entries_toolbar(false);
      } else if (num_selected == 0) {
        $('#entries-selector').removeAttr('checked');
        $.toggle_entries_toolbar(false);
      }
  });

  $('#entries .title .outer .inner a').click(function() {
    $(this).css('font-weight', 'normal');
  });

app/views/rss_streams/_form.html.haml
= form_for(@rss_stream, :remote => true) do |f|
  #errors_explanations
  -if @rss_stream.id.present?
    .input-prepend.float-left
      %span.add-on
        %i.icon-tag
      = f.text_field(:title, {:placeholder => "Title", |
                              :class => "span2", |
                              :size => "50"}) |
    %br

  .input-prepend.float-left
    %span.add-on
      %i.icon-rss
    -if @rss_stream.id.present?
      = f.text_field(:url, {:placeholder => "URL", |
        :readonly => "readonly", :class => "span2", |
        :size => "50"}) |
    -else
      = f.text_field(:url, { :placeholder => "URL", |
        :class => "span2", :size => "50" }) |

  %p{:class => float_right_or_not(@rss_stream.id.present?)}
    %a#submitSub.btn.btn-info{:onclick => 'loadInsideSpin(this); $(this).parent().parent().submit();'}
      %i.icon-ok
    -if @rss_stream.id.present?
      %a.btn{:onclick => "$('#edit_sub_btn').popover('destroy'); edit_subscription_lock = false;"}
        %i.icon-remove
    -else
      %a.btn{:onclick => "$('#new_sub_btn').popover('destroy'); new_subscription_lock = false;"}
        %i.icon-remove

app/views/rss_streams/_index.html.haml
%table
  %tr
    %th Title
    %th Url
    %th
    %th
    %th
  - @rss_streams.each do |rss_stream|
    %tr
      %td= rss_stream.title
      %td= rss_stream.url
      %td= link_to 'Show', rss_stream
      %td= link_to 'Edit', edit_rss_stream_path(rss_stream)
      %td= link_to 'Destroy', rss_stream, method: :delete, data: { confirm: 'Are you sure?' }
%ul
  - @entries.each do |entry|
    %li= entry.name

app/views/rss_streams/_new.html.haml
= render :partial => 'rss_streams/form'

app/views/rss_streams/_show.html.haml
#panel_splitter
  #feed_entries_list
    %h3#stream_title
      - if @rss_stream.present?
        = @rss_stream.title
      - elsif params[:action] == 'starred'
        Starred items
      - else
        All items
    %p#toolbar
    .btn-group.open{:style => "display: inline;"}
      %a.btn{:href => "#", :style => "backgound-color:red;"}
        %input#entries-selector{:type => "checkbox"}/
      %a#toggle-link.btn.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
        %span.icon-caret-down
      %ul.dropdown-menu
        %li
          %a{:href => "#"} All
        %li
          %a{:href => "#"} None
        %li
          %a{:href => "#"} Read
        %li
          %a{:href => "#"} Unread
        %li
          %a{:href => "#"} Starred
        %li
          %a{:href => "#"} Unstarred
    %span#entries-buttons
      - if @rss_stream.present?
        \&nbsp;&nbsp;
        \#{link_to('<i class="icon-repeat"></i> Reload'.html_safe, @rss_stream, { :remote => true, :class => "btn loadable", :onclick => "loadSpin();" })}
        \&nbsp;
        \#{link_to('<i class="icon-edit icon-large"></i> Edit'.html_safe, edit_rss_stream_path(@rss_stream), { :id => "edit_sub_btn", :class => "btn", :remote => true })}
        \&nbsp;
        \#{link_to('<i class="icon-trash icon-large"></i> Delete'.html_safe, @rss_stream, { :class => "btn btn-danger", :confirm => "Are you sure ?", :method => :delete, :remote => true })}
        \&nbsp;
    %span#selected-entries-buttons
      \&nbsp;&nbsp;
      .btn-group
        %a.btn{:href => "#", :onclick => "loadSpin(); $.star_item();", :title => "Star"}
          %i.icon-star
        %a.btn{:href => "#", :onclick => "loadSpin(); $.unstar_item();", :title => "Unstar"}
          %i.icon-star-empty
        %a.btn{:href => "#", :onclick => "loadSpin(); $.mark_as_read();", :title => "Mark as read"}
          %i.icon-eye-open
        %a.btn{:href => "#", :onclick => "loadSpin(); $.mark_as_unread();", :title => "Mark as unread"}
          %i.icon-eye-close
        - if params[:action] == 'trash'
          %a.btn{:href => "#", :onclick => "loadSpin(); $.restore_item();", :title => "Restore"}
            %i.icon-undo
        - else
          %a.btn{:href => "#", :onclick => "loadSpin(); $.remove_item();", :title => "Remove"}
            %i.icon-trash
    \&nbsp;&nbsp;
    %span#loading
      %i.icon-spinner.icon-spin.icon-large
      Loading...
    #entries-box
      = render 'rss_streams/entries'
  #preview

app/views/rss_streams/create.js.erb
<% if @rss_stream.errors.any? %>
  $('#errors_explanations').html(
      "<%= escape_javascript(
        output_errors(@rss_stream.errors)).html_safe %>");

  //var new_height = parseInt($("#new_subscription form").height()) + 10;
  //$("#new_subscription").css('height', new_height + "px");
<% else %>
  var html = "<%= escape_javascript(
           render('home/streams', :collection => @streams)) %>"
  $("#streams_list").html(html)
  $.notify("RSS/Atom feed successufuly added !", "success")
  $('#new_sub_btn').popover('destroy');
  new_subscription_lock = true;
<% end %>

unloadInsideSpin($('#submitSub'));

app/views/rss_streams/destroy.js.erb
var html_content = "<%= escape_javascript(
         render(:template => 'home/index', :collection => @entries)) %>"

var html_streams = "<%= escape_javascript(
         render('home/streams', :collection => @streams)) %>"

$("#content").html(html_content)
$("#streams_list").html(html_streams)

app/views/rss_streams/edit.js.erb
if (!edit_subscription_lock) {
  var html = "<%= escape_javascript(
    render(:partial => 'rss_streams/edit')) %>"
  //$("#edit_subscription").html(html);

  //$("#edit_subscription").dialog("open");
  $("#edit_sub_btn").popover({
    html: true,
    placement: 'bottom',
    title: 'Edit subscription',
    content: html
  });

  $("#edit_sub_btn").popover('toggle');

  // enable lock
  edit_subscription_lock = true;
} else {
  $("#edit_sub_btn").popover('destroy');

  // disable lock
  edit_subscription_lock = false;
}

app/views/rss_streams/index.js.erb
var html = "<%= escape_javascript(
  render(:partial => 'rss_streams/index')) %>"
$("#content").html(html)

app/views/rss_streams/new.js.erb
if (!new_subscription_lock) {
  var html = "<%= escape_javascript(
    render(:partial => 'rss_streams/new')) %>"

  $('#new_sub_btn').popover({
    html: true,
    title: 'New subscription',
    content: html
  });

  $('#new_sub_btn').popover('toggle');

  // enable lock
  new_subscription_lock = true;
} else {
  $('#new_sub_btn').popover('destroy');

  // disable lock
  new_subscription_lock = false;
}

app/views/rss_streams/show.js.erb
var html = "<%= escape_javascript(
  render(:partial => 'rss_streams/show')) %>"

$("#content").html(html);
$("#loading").css("visibility", "hidden");
$("#panel_splitter").splitter();

// add a preview icon into the preview area
$('#preview').html(
    '<div id="preview-icon-box">\
      <i class="icon-search icon-large"></i>\
    </div>');

$('#preview').css('height', $('#panel_splitter').height() + 'px');

// center vertically the preview icon box
$('#preview-icon-box').css('margin-top',
  ($('#preview').height()/2) - 42 + 'px');

// trick to close the dropdown menu
$('#toggle-link').click();
$('#toggle-link').blur();

// Auto adapt the size of the entries list container
$('#entries-box').css('height', $('#feed_entries_list').height()-90 + 'px');


// add action handlers on toolbar buttons
entries_selected = false;
$('#entries-selector').change(function() {
  $.toggle_entries_toolbar(true);
});

$('a').tooltip({'placement':'bottom-left', 'delay':{'show':500, 'hide':100}});

// handle custom scrollbars
$('#entries-box').perfectScrollbar({
  wheelSpeed: 30
});

app/views/rss_streams/update.js.erb
<% if @rss_stream.errors.any? %>
  $('#errors_explanations').html(
      "<%= escape_javascript(
        output_errors(@rss_stream.errors)).html_safe %>");

  /*var new_height = parseInt($("#edit_subscription form").height()) + 10;
  $("#edit_subscription").css('height', new_height + "px");*/
<% else %>
  //$("#edit_subscription").dialog("close");
  $('#edit_sub_btn').popover('destroy');

  // disable lock
  edit_subscription_lock = false;

  var html = "<%= escape_javascript(
           render('home/streams', :collection => @streams)) %>"
  $("#streams_list").html(html)
  $("#stream_title").html("<%= escape_javascript(@stream_title) %>")
  $.notify("RSS/Atom feed successufuly updated !", "success")
<% end %>